mode: "train"  
# train / test / augmentation / hyperparameter_tune / ensemble
random_seed: 20010316
device: "cuda"

wandb:
  user_name: "euiin_deit"
  team_name: "gaemanssi2-naver-ai-boostcamp"

paths:
  save_dir: "./outputs/saved_models"
  output_dir: "./outputs/"